[lint]
ignore = [
  "D1",
  "E501",
]
select = ["ALL"]

[lint.per-file-ignores]
"tests/**/*.py" = [
  "S101",
]

[lint.isort]
required-imports = [
  "from __future__ import annotations",
]

[lint.pydocstyle]
convention = "google"
